language: php

install:
  - travis_retry composer install --prefer-dist --no-interaction --no-suggest

script:
  - vendor/bin/phpunit --verbose --coverage-clover build/logs/clover.xml

after_success:
  - if [[ $COVERAGE = 'true' ]]; then bash <(curl -s https://codecov.io/bash); fi


matrix:
  include:
    - php: 7.0
      env: SETUP=lowest
    - php: 7.0
      env: SETUP=stable
    - php: 7.1
      env: SETUP=lowest
    - php: 7.1
      env:
        - COVERAGE=true
        - SETUP=stable
        - DEPLOY_DOCS=true
    - php: nightly