#!/usr/bin/env php
<?php
/*
 * This file was adapted in part from PHPUnit.
 * (c) Sebastian Bergmann <sebastian@phpunit.de>
 */
if (version_compare('7.1.0', PHP_VERSION, '>')) {
    fwrite(
        STDERR,
        sprintf(
            'This version of bretterer/openapi-codegen requires at least PHP 7.1.' . PHP_EOL .
            'You are using PHP %s (%s).' . PHP_EOL .
            'For information on this decision, visit https://gophp71.org/' . PHP_EOL,
            PHP_VERSION,
            PHP_BINARY
        )
    );

    die(1);
}

if (!ini_get('date.timezone')) {
    ini_set('date.timezone', 'UTC');
}

foreach ([
    __DIR__ . '/../../autoload.php',
    __DIR__ . '/../vendor/autoload.php',
    __DIR__ . '/vendor/autoload.php'
     ] as $file) {
        if (file_exists($file)) {
            define('OPENAPI_COMPOSER_INSTALL', $file);

            break;
        }
    }

unset($file);

if (!defined('OPENAPI_COMPOSER_INSTALL')) {
    fwrite(
        STDERR,
        'You need to set up the project dependencies using Composer:' . PHP_EOL . PHP_EOL .
        '    composer install' . PHP_EOL . PHP_EOL .
        'You can learn all about Composer on https://getcomposer.org/.' . PHP_EOL
    );

    die(1);
}

require OPENAPI_COMPOSER_INSTALL;

